dataset_name: cnn_dailymail
data_experiment_name: base
generator_name: zephyr
batch_size: 64

# which scorer to use in the pipeline
use_bert_scorer: True
use_idf_scorer: True
use_prometheus_scorer: False
use_ppl_scorer: True

compare_ai_to_human: False

# watermarking_scheme
watermarking_scheme_name_main: KGW
watermarking_scheme_name_compare: no_watermark

save_res_dir: text_quality_eval_results
