type: no_attack
attack_name: no_attack
attack_type: no_attack
experiment_name: base
dataset_size: 100
max_sample_len: 500
prefix_size: 10
max_new_tokens: 220
min_new_tokens: 200
dataset_name: cnn_dailymail
generator_name: qwen2_chat_0_5B
user_prompt: "You are a helpful assistant."
system_prompt: "Continue writing the following news article starting with:"
batch_size: 2

data_folder: data/generated_datasets
skip_cache: False
skip_train_split: False